# Generated by Django 2.2.7 on 2020-07-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=124)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_product',
        ),
        migrations.AddField(
            model_name='category',
            name='my_type',
            field=models.IntegerField(choices=[(1, 'PANADERIA'), (2, 'TIENDA')], default=1),
        ),
        migrations.RemoveField(
            model_name='product',
            name='presentation',
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=124)),
                ('amount', models.FloatField(default=0.0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.Unit')),
            ],
            options={
                'verbose_name': 'Presentacion',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit_base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_products.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.ManyToManyField(related_name='MyPresentation', to='app_products.Presentation'),
        ),
    ]
