# Generated by Django 2.2.7 on 2020-07-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_auto_20200710_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=248),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.ManyToManyField(related_name='MyPresentations', to='app_products.Presentation'),
        ),
    ]
