# Generated by Django 2.2.7 on 2020-07-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_auto_20200715_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='presentation',
        ),
        migrations.CreateModel(
            name='ProductPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_sale', models.FloatField(default=0.0)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.Presentation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='presentations',
            field=models.ManyToManyField(through='app_products.ProductPresentation', to='app_products.Presentation'),
        ),
    ]
