# Generated by Django 2.2.7 on 2020-07-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_auto_20200716_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='my_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_sale',
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='00001', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(default='0001', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpresentation',
            name='code',
            field=models.CharField(default='0001', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='abbr',
            field=models.CharField(default='0001', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presentation',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
