# Generated by Django 2.2 on 2020-07-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_auto_20200716_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpresentation',
            options={'verbose_name': 'Mi presentacion', 'verbose_name_plural': 'Mis presentaciones'},
        ),
    ]
