# Generated by Django 2.2.7 on 2020-07-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0007_auto_20200717_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
