# Generated by Django 3.0.8 on 2020-08-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0011_auto_20200802_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpresentation',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productpresentation',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
