# Generated by Django 2.2 on 2020-06-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200629_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.CharField(default='und', max_length=16),
            preserve_default=False,
        ),
    ]
