# Generated by Django 2.2.7 on 2020-07-25 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('app_products', '0007_auto_20200717_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('last_date', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO'), (3, 'MIXTO')], default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=16)),
                ('percentage_price', models.FloatField(default=0.0)),
                ('fixed_price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_inventories.Action')),
                ('invoice', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
            bases=('app_inventories.action',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_inventories.Action')),
                ('invoice', models.CharField(max_length=32)),
                ('mode', models.IntegerField(choices=[(1, 'LOCAL'), (2, 'DOMICILIO')], default=1)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
            bases=('app_inventories.action',),
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('type', models.IntegerField(choices=[(1, 'CASH'), (2, 'CREDIT_CARD'), (3, 'DEBIT_CARD'), (4, 'PSE'), (5, 'BRANCH')], default=1)),
                ('payment', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventories.Action')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='ActionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventories.Action')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.ProductPresentation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.Product')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='duties',
            field=models.ManyToManyField(blank=True, to='app_inventories.Duty'),
        ),
        migrations.AddField(
            model_name='action',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app_inventories.action_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
