# Generated by Django 2.2.7 on 2020-07-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0008_product_capacity'),
        ('app_inventories', '0002_auto_20200725_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionProduct',
            new_name='Detail',
        ),
        migrations.AlterField(
            model_name='buy',
            name='invoice',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='duty',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
