# Generated by Django 3.0.8 on 2020-07-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventories', '0003_auto_20200725_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='duties',
            field=models.ManyToManyField(blank=True, to='app_inventories.Duty'),
        ),
    ]
