# Generated by Django 3.0.8 on 2020-08-05 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventories', '0003_auto_20200805_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 0, 30, 55, 30747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='action',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 0, 30, 55, 30801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 0, 30, 55, 33435, tzinfo=utc)),
        ),
    ]
