# Generated by Django 3.0.8 on 2020-08-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventories', '0004_detail_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='duty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
