# Generated by Django 2.2.7 on 2020-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventories', '0005_auto_20200801_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='fixed_price',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='percentage_price',
        ),
        migrations.AddField(
            model_name='detail',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='duty',
            name='is_percentage',
            field=models.BooleanField(default=True),
        ),
    ]
