# Generated by Django 3.0.8 on 2020-08-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventories', '0006_auto_20200802_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='duties_details',
            field=models.FloatField(default=0.0),
        ),
    ]
