# Generated by Django 3.0.8 on 2020-08-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventories', '0027_auto_20200805_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='action',
            name='last_date',
            field=models.DateTimeField(),
        ),
    ]
