# Generated by Django 3.0.8 on 2020-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventories', '0030_auto_20200805_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
